### ISSUE TITLE
Add meta plugin support

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#11]
With bindings, plugins will need to go and find other plugins to work properly (eventd shouldn't know how to load a Ruby or Python plugin). Instead, a single Python plugin should have functions which go off and find Python modules which are plugins.

My idea is to have 3 symbols which are functions: one which returns a list of ids, another to get the context for an id and another for the `get_interface` function. The problem is that some state needs to be passed to the `get_interface` function (or some global state needs to be tracked *ugh*). Maybe better would be to pass a function which the meta plugin calls to register the plugins it finds back with the server? Unloading will also be interesting since the module can't be closed until all children plugins have been dealt with.

**Comment by sardemff7** [comment]
I am currently experimenting around your GI work to provide script language plugins.

Once I will have the whole design settled, I will probably push something either to a branch in eventd or as a separated repository.

**Comment by mathstuf** [comment]
Alright, sounds good. Thanks.

**Comment by sardemff7** [comment]
Got Ruby and Python working quite well.
Ruby is not Exception-safe at all for now, so a plugin must define all the methods.

Code at [eventd-bindings](https://github.com/sardemff7/eventd-bindings).

Closing this issue, please open one on eventd-bindings if needed. :-)
