### ISSUE TITLE
expose hints for notifications

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#20]
There should be a way to fill out hints for notifications from the config file. Something like:

```conf
[Libnotify]
Hints=foo;bar
Hint_foo=${some_field}
Hint_bar=${some_other_field}
```

https://developer.gnome.org/libnotify/0.7/NotifyNotification.html#notify-notification-set-hint

**Comment by sardemff7** [comment]
Good idea. Just let me think about these “hashtable keys”, whether there should be a generic helper in libeventd or not.

**Comment by mathstuf** [comment]
Ew. If you want to hack it up:

```
Hint[foo]=${some_field}
```

and then query it with `_locale_string`.

**Comment by sardemff7** [comment]
Done in 18f2eeedd740bbbc2a15da58ce6dea906b9b5c83, enjoy!
