### ISSUE TITLE
Bad G_LOG_DOMAIN detection

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#22]
I'm seeing this in my build logs locally:

```
 -D G_LOG_DOMAIN=\"boeckb\"
```

Which seems…wrong :) .

**Comment by mathstuf** [comment]
This is due to me using an out-of-source build. It would be better to compute the domain from the *end* of the word list, but I don't see how to do a math expression to compute it from `$(words)`.

**Comment by sardemff7** [comment]
Fixed in a25fb6d4a249d5683ffbf19abca044744afe289c, available in 0.6.1 release.

**Comment by mathstuf** [comment]
That works too :) .
