### ISSUE TITLE
Error (or at least warn) when an action doesn't have a backend

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#24]
Currently, not having the `notify` plugin doesn't output that anything is amiss when a `Libnotify` action is attempted.

**Comment by sardemff7** [comment]
Now, the `fdo-notifications` plugin is both server and client.
It will silently discard the client part when it gets the D-Bus name, to avoid any loop.

I just pushed 328347bdb3f8bd3f592eee0fae17c49a63d4250a to build client support by default, so now the only way to lack client support is to pass `--disable-libnotify`.

The big difference is that now, `fdo-notifications` has a dependency on gdk-pixbuf too (unless for source-based distribution or if you build twice the package to get both versions).

I think this should work for most setups, as the DE notification-daemon should be started before eventd.

In which case would you like an error/warning?
While writing, I though about a case and pushed 47dc4d53837e15b9e8e240f2e78959cc33a483ea, is that what you meant?

**Comment by mathstuf** [comment]
The problem is that I didn't have the plugin at all, not that it wasn't working :) .

**Comment by sardemff7** [comment]
Oh, yeah, the `notify` plugin is now gone. :-)
It is part of the `fdo-notifications` plugin, with only a dependency on gdk-pixbuf, as I directly use D-Bus calls now, skipping libnotify.

I think I will actually split it again, because the issue was really libnotify and its lack of monitoring…
Stay tuned.

**Comment by mathstuf** [comment]
It is in master, but not in 0.7.2, but that is not relevant here. The problem is that I installed eventd and eventd-plugin-journald, but had forgotten eventd-plugin-notify. Eventd gave no indication that anything was wrong with sending notifications. It should say that an action you specified has no available implementation.

**Comment by sardemff7** [comment]
That is impossible.
The plugin is checking its configuration on its own. eventd has *no idea* that there exists a `notify` plugin that checks for a `Libnotify` section.
The action only exists if the plugin is there and actually checks the section.
Even if eventd was checking the section, it would still need the plugin to get the section name. Also, plugins like `relay` and `im` are using more than one section, and the actual names are configuration-dependent (the `[Server <name>]` and `[Account <name>]` sections).

How would you add such a warning?

**Comment by mathstuf** [comment]
Hrm, true. Maybe eventd could at least log which plugins it loaded so that one missing could be more easily seen.

**Comment by sardemff7** [comment]
It does, if you `--enable-debug`. :-)

**Comment by mathstuf** [comment]
It's something that might be more important than as debugging output :) .

**Comment by sardemff7** [comment]
You should not expect something without the corresponding plugin.

I would consider that someone installing plugins should know which one are installed. :-)

Maybe just add a `Recommends:` for the `notify` plugin too? :-)

**Comment by mathstuf** [comment]
It doesn't belong as a `Recommends:`. I'll just add it to my `comps.xml`.

**Comment by sardemff7** [comment]
Ok.

I use `--enable-debug` here, so you *may* want to just set that for your package. It just enables extra output.
