### ISSUE TITLE
is it possible to have a middle top/bottom notification box placement ?

### ISSUE THREAD

**Issue by Lompik** [sardemff7/eventd#27]
All previous reports where my own mistakes! 

`bottom left/right` works as expected, no issues. However would it be possible to have bottom middle box placement ?

**Comment by sardemff7** [comment]
A bit tricky considering the placement code, but doable. I will work on that.

**Comment by sardemff7** [comment]
Ok so the first step was to move the placement logic to the backends. I pushed 9cb1be63d74f2a7202a5eca7cc094f87a1c86858 for that.
You need to update your configuration to use `[NotificationXcb]` instead of `[Notification]` for placement keys, see the updated man page.

**Comment by sardemff7** [comment]
Here you are, pushed 856997434c1e66d429927e74877f6cff62306276 to support top/bottom centered placement!
