### ISSUE TITLE
dbus, gir, and systemd files not installed

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#29]
Not sure what's causing the problem here. Not detecting as Unix? Works in an old buildtree of mine, but the RPM isn't picking them up anymore. [Build logs](https://copr-be.cloud.fedoraproject.org/results/mathstuf/eventd/fedora-rawhide-x86_64/00148894-eventd/build.log.gz).

**Comment by sardemff7** [comment]
A bit hidden since I do not check the value of the various `*dir` I get from pkg-config:
```
Unknown option --dont-define-prefix
```
The option was Windows-specific before [pkg-config 0.29](http://cgit.freedesktop.org/pkg-config/commit/main.c?id=43c1e0e4afa341ea7e4710de4dd81b0074948e68).

Preparing a fix.

**Comment by sardemff7** [comment]
Pushed 7fbfa341d6828335d01d16ac2e2a7f378de415f5.
