### ISSUE TITLE
How to start eventd properly

### ISSUE THREAD

**Issue by averrin** [sardemff7/eventd#36]
I try to use eventd in my arch + wayland + sway setup.
It works fine only when i start `eventd` in terminal, but i cannot find right `eventdctl` command to start it in background.

**Comment by sardemff7** [comment]
Please use the IRC channel for such questions.

Under Sway, eventd’s nd plugin can work with either the Wayland backend (you’ll have to use the [WLC injector](https://github.com/wayland-wall/orbment-wall#injector) in that case) or the X11 backend (via Xwayland). The Wayland backend is preferred if the `$WAYLAND_DISPLAY` env var is present, it is not built in the AUR packages.
The commands to run are, in each case:
- `eventdctl --auto-spawn nd switch wayland $WAYLAND_DISPLAY`
- `eventdctl --auto-spawn nd switch xcb $DISPLAY`
The `switch` is not needed if the default backend (based on env) is good for you.
That means you can run `eventdctl start` only, in your Sway config, and it should work.

I still encourage the systemd way, where eventd is run as a systemd user unit, and you use `eventdctl switch` (no `--auto-spawn`) to connect the backend. [session-nanny](https://github.com/sardemff7/session-nanny/) can be used to switch the backend automatically when you switch sessions, if you have more than one.
