### ISSUE TITLE
systemd unit broken (eventd-git arch linux)

### ISSUE THREAD

**Issue by AhmedAA** [sardemff7/eventd#38]
I cannot seem to get the systemd unit to work under arch linux with the `eventd-git` package from AUR.

I get the following output:
```
# aaa at noctis in ~ 
→ systemctl status eventd.service
● eventd.service - eventd
   Loaded: loaded (/usr/lib/systemd/system/eventd.service; indirect; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-02-26 16:07:50 CET; 7s ago
     Docs: man:eventd(1)
           man:eventd.conf(5)
           https://www.eventd.org/
  Process: 8812 ExecStart=/usr/bin/eventd --listen systemd --system (code=exited, status=217/USER)
 Main PID: 8812 (code=exited, status=217/USER)

Feb 26 16:07:50 noctis systemd[1]: Starting eventd...
Feb 26 16:07:50 noctis systemd[8812]: eventd.service: Failed to determine user credentials: No such process
Feb 26 16:07:50 noctis systemd[8812]: eventd.service: Failed at step USER spawning /usr/bin/eventd: No such >
Feb 26 16:07:50 noctis systemd[1]: eventd.service: Main process exited, code=exited, status=217/USER
Feb 26 16:07:50 noctis systemd[1]: eventd.service: Failed with result 'exit-code'.
Feb 26 16:07:50 noctis systemd[1]: Failed to start eventd.
```

**Comment by sardemff7** [comment]
Do you really want to run eventd system instance? If you do, you need to either create an eventd user or change the user in the unit (via a drop-in file, do not touch the installed unit files).
If you don’t, or if you don’t know, then see `systemctl --user`.

**Comment by AhmedAA** [comment]
Hmm.. I tried reading up on it, I am sorry if I misunderstood something.
I am trying to use eventd as a local notification service.
Running it in my .xinitrc with a `eventd &` line works fine. I am basically trying to achieve the same as just running it like that.

Again sorry if I overlooked something, and thank you very much for your time!

**Comment by AhmedAA** [comment]
Urgh, I am so sorry for wasting your time..

To anyone else who might happen to find this in the future:
run `systemctl --user enable eventd` and `systemctl --user start eventd`

I guess I need to read up on some documentation..

**Comment by sardemff7** [comment]
No time wasted, I’ll add some more verbosity in the man page.
eventd is a user service, using `systemctl` alone is for system services.

If you have an user instance of systemd running, then enabling eventd is as simple as `systemctl --user enable eventd`.
You actually should start the sockets `eventd.socket` and `eventd-control.socket` rather than eventd itself (or just restart your session so that systemd does it).

**Comment by sardemff7** [comment]
Added a man page notice in 9d41cbf98aaec531ffee06de856bc164f080c79e.

**Comment by AhmedAA** [comment]
@sardemff7 more explicit now at least :)

cheers for your help!

and btw i really like the idea with this.. very nice work you have done!
(i got inspired from this, should be interested :) https://github.com/p3lim/dotfiles)
