### ISSUE TITLE
Enable gobject-introspection

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#4]
Should allow event plugins to be written in other languages.

**Comment by mathstuf** [comment]
Going through, adding documentation and there's no way to mark `libeventd_reconnect_new` up properly because the lifetime of `callback` needs a `GDestroyNotify` argument to be proper.

**Comment by sardemff7** [comment]
I am adding some new stuff to `libeventd` (now renamed from `libeventd-event` so I keep this issue opened until it is done.

**Comment by sardemff7** [comment]
I think everything is done now, closing. :-)
