### ISSUE TITLE
Settings ignored

### ISSUE THREAD

**Issue by natsukagami** [sardemff7/eventd#42]
I'm using eventd solely for its `nd` plugin - getting and displaying notifications.

Here's my config (now being placed both in `~/.config/eventd/eventd.conf` and `/usr/share/eventd/eventd.conf`):

```
[NotificationText]
Font=Terminus 16px
Colour=#DDDDDD

[NotificationBubble]
Colour=#00FF00
```

Nothing changes when I try to `notify-send Title Message`. The notification with default notification theme is displayed.

I'm running eventd on Arch Linux x64 (i3 window manager), `eventd` package from [AUR](https://aur.archlinux.org/packages/eventd/) installed without any modifications.

**Comment by sardemff7** [comment]
`eventd -t` is a bad idea, it deletes the existing sockets to create its own, which is only useful if the previous one crashed, or on Windows.
Restarting or reloading the systemd unit should work, but it won’t if the sockets were deleted. In this case, you have to restart the socket units in systemd too.
`eventdctl reload` is the command to reload, and `systemctl --user reload eventd` (note the `--user`) is actually doing just that.

**Comment by natsukagami** [comment]
Alright, thanks for the info! Sorry for the unneeded issue.
