### ISSUE TITLE
Release tarballs don't contain submodules

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#46]
The releases on Github don't contain the `libgwater` and `libnkutils` sources in them. I'd recommend using [`git-archive-all`](https://github.com/Kentzo/git-archive-all) to create the release tarballs.

**Comment by sardemff7** [comment]
I do not use Github releases, they’re just automatically-created archives based on tags. For releases, please check [eventd’s website](https://www.eventd.org/download.html).
