### ISSUE TITLE
Placement issue with Sway

### ISSUE THREAD

**Issue by joefiorini** [sardemff7/eventd#48]
I was able to compile eventd with the Wayland backend on my Arch installation running the latest swaywm (here is [the meson-log output relevant to the Wayland backend](https://gist.github.com/joefiorini/e8a8d6d6157e1fa2995bdaa0ef432d62). However, running `eventdctl nd backends` still only shows `xcb` and `eventdctl nd switch wayland $WAYLAND_DISPLAY` results in event notifications not showing anything. On top of that I'm noticing that running with the xcb backend, notifications grab focus from the currently focused window. I also have a second display plugged in (running off a laptop in clamshell mode) and the notification is positioned relative to the laptop's display, not the external one.

I'm assuming the latter issue is due to not being able to use the Wayland backend. I'm also assuming that the Wayland backend is not working because Sway does not implement your notification area protocol. Can you help me verify if those assumptions are correct or if it should work and maybe there's another issue?

Thanks!

EDIT: Is there a reason now not to use the WLR layer shell spec instead? That seems like the ideal way to implement notifications that would be compatible with the most compositors (anything built on wlroots for a start).

**Comment by sardemff7** [comment]
I am 100% against the `layer-shell` protocol from wlroots at a design level. It is a catch-all protocol aiming solely to reproduce the worst in X11 : any client can just do whatever it wants without the compositor having a say to do things right.
Sadly, Sway’s developer had a much larger user base, more time to code, hence the extra traction.

Though I wouldn’t officially support that, anyone can provide a drop-in replacement for the `nd` Wayland backend, or even fork eventd altogether, or just `nd`. I couldn’t care less, as Sway and wlroots have drained every single drop of motivation I had about Wayland for now. (I even have a draft for an even better protocol than `notification-area` locally, but it’s unlikely to ever be implemented in a compositor (I do have a libweston implementation locally too but hey).)
Feel free to convince them to implement another protocol, I’ll gladly maintain code for it.

As for the XCB backend, it’s either an XWayland bug or a Sway/wlroots XWayland code bug. `nd` **never** asks for a grab, so XWayland should not either, thus I would suspect wlroots code.
Please reopen this bug if you can find something `nd` specifically does to trigger that.
